#version: '3.9'
services:
  app:
    image: "terraio_v1"
    container_name: "terraio"
    network_mode: "host"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:11081:3000"
