const favicon = `AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAMMOAADDDgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoAAAAqAAABLQEABi0EAAstAwAHKwAAASsAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALxIAAC4QAAIvEwAjLxwDXzEpDpMyNhqzMzsfvzI1
GbUwJQuPLxgBSy8UAA0vEwAAMBkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHADAdAwAwHgQkMSgOjjRIK+A3bk79
Oodk/zuPbP87k2//PJt2/zuXc/83Z0f2MS4TtC8YADc2OhwAMB4FAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcAMB8FKzEo
Ds01UTP/N2RE/TVUNegzPyPJMjMXrzEwFakyOx7ENmJC8j2rhf89o37/M0Qn4DAaAUcwIgcAKwkA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADAhBwAwIQeGMCQK4TErEKIwHQReLhEAKi4KAA4sAAAEKgAAAi4KAA0vFgBJMjQYxjuTb/8/
vZb/OoVjtDAgBykzPhsALQkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAMCEHADAhByMwIAYgLhAAAy8WAQAnAAAAAAAAAAAAAAAAAAAALxsB
AC8ZAAAvFAAfMSsQsjuTb/8/u5P/NEQntDAhBwkyNhoAAAAAAAAAAAAAAAAAMCEHADAhBwUwIQcE
MCEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAMCEHAC8bAgAvFQAfMjEWwj2ngv8/v5fjM0QnUBUAAAEwIQcAMCAGAC1L
FAAxEwAPMCAGdTAhB1IwIQcBMCEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHADAdAwAvFgA7NE4w5j+5kv80Rina
LxMAIjAhBwAwIQcAMB8FNS8yF8MvKxH1MCAGzjAhBycwIQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHACgA
AAAwIAaFOoxp/zqDYf8wHAN1MSkNACxeQAAwJgyVKnxc/y5DJ/MwHwXJMCEHTzAhBwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAMCAGAC8SAC41VTboP7mR/zNCJuAvGgFlLxAADzAnDJcpi2v/LFk78jAaAGcw
IQcOMCEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcALg8AHjRIK95B06r/QMGZ/zduTfoxLhOxMBoA
gS1OMvQnnXv/LkMn4DAbATQwIQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADAhBwAwIQcAMCEHCDAgBhUwHAJSMRkBSDEZAQYvFgBHN2tK90PjuP9D
57z/Q+G3/z2kfv8zQCPuLkEl+SW+mv8rbU7/MBwCZzAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHADAhBwEwIQdzMCIIzCxVOPssVzr3MCUK
gTAcA3U6imf/Q+i9/0Pluv9D5br/Q+i8/0DAmP8zXD3/LFo8/i8zGL0wHAMjMCEHAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcAMCEHADAhB2ow
IQf4LkUp9iiZeP8tSS3lMB4EuDyceP9D6L3/Q+W6/0Pluv9D5br/Q+i8/z/AmP8zQSTzLxgASzAc
AgAwIQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ADAhBwAwIQcAMCEHKjAhB7EwGgGPKnJS+yp5Wf0wKxD3PKF8/0Povf9D5br/Q+W6/0Pluv9C37T/
Ooxp/zqGY/8xLhOpLhEACDAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAADAhBwAwIQcEMCEHHDEWAEQsXkD1JcSf/ytmSP88l3P/Q+i9/0Pl
uv9D5br/Q+W6/0Pmuv86iGX/OHZV/zZcPe8vFgA7MgIABTENABExDAADMQ4AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcAMRkAGS80GMQsWz33
LjYa8DmCX/5D57z/Q+W6/0Pluv9D5br/Q+a7/0HSqf8+r4j/O49s/zAfBa0vLxSuLj0hzy8sEZsw
IAdEMCEHPDAhBy0vIAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAh
BwA1AAAAMRsDHzEVADwvFQBbNl9A9ELgtv9D5br/Q+W6/0Pluv9D5br/Q+a7/0Pqvv8+sYv/L0Up
/yiPbv8qfV3/LFU4/zAmC/YwIQfcMCEHYzAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHAC8SABUyORzNQMGZ/0PnvP9D5br/Q+W6/0Pluv9D
5br/Q+e8/0C9lf8uYEL/KnBR+zAkCqcwJw2fMCII6TAhB7QwIQcnMCEHAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcAMScMADAeBHY5e1r+Q+W6
/0Pluv9D5br/Q+W6/0Pluv9D57z/QL+Y/zBHKv8uOR3aMRUAIDEaBQIwIQeEMCEHfzAhBwIwIQcA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAEAADAYAAAy
EAALMBkBZDExFfU+rIb/Q+i9/0Pluv9D5br/Q+W6/0PnvP8/vJT/MS4T4zAeBVgwIgcBMCEHADAh
BxIwIQcrMCEHADAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAuPSIALjccCy43HKEsX0H2KYRk/zFWOP8+sIr/Q+a7/0Pmu/9D5br/Q+e8/0DCmv8yNRrE
LgsADjAgBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAMCEHAAD//wArZUdMJ5996ymEZP8olXP/KYFh/zE6Hvw6iGX+Qtiu/0Pm
u/9D5br/Qt60/zdoSPcwGwJqLQ8AATAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcAMRMAFi45Hs0sXT/+MCMJoS8nDZovNhrK
MCIIejAfBpc5f139Q+W6/0Pluv9D57z/QMmh/zRNL+gvGgFEMCAGADAhBwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHADAhBw4wIQeNMCQK+zAl
CtswHQMeMwAAAjEQAA4qZSsALhAAMzZbPO9C37X/Q+W6/0Pluv9D6L3/PamD/zErEMUvGQAXMCAG
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIQcA
MCEHMzAhB6AwIQfKMCEHxTAhByYwIQcAAAAAADAhBwAvEwA9N2ZG9EPkuf9D5br/Q+W6/0Pmu/85
hmP/Lzgd/jAkCnsvKxAAMCEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAADAhBwAwIQcCMCEHDzAhBy4wIQd0MCEHLDAhBwAAAAAAMCEHAC8WAEM2X0D3Qcqh
/0PjuP9D5br/Q+W6/zmBX/8vPSH/MCUKiS8sEQAwIQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuIQcAMCEHADAhBwQwIQcCMCEHAAAAAAAw
IQcAMB0DKTAuE+YxSy7/Pq+I/0PnvP9D5rv/Qtmv/zZfQPwvGQBVMCEHAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAADAhBwAxFwAMLywRtS86H/88nnn/Q+m9/0Povf9B1q3/NE8x5C8TACkwIQcA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCEHADAaAQAwHQMjMCEHojh0U+pC1qzyQMKa/zmB
X/8xJgyVLgwAAzAhBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSIHAC8cBAAvFQAM
MzsjKTh2VFUyNxu4MScMkzAdAxwwHgQAMCAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAArAQAAKwEAAS0FAAguCAADLQYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/B//
/+AH///AA///gAH//4AA//+P4Hz///A4f//4MH///DB///wAf//8AH//gAB//wAAf/+AAP//gAB/
/4AAD//gAAH/8AAB//wAAf/+AAH//AAT//gAP//4AB//8AAf/+AgD//g4A//4OAP//zgD///4A//
//AP///4H////j8=`;

const css = `
body
    {
    width: 100%;
    color: white;
    background-color: #121212;
    font-family: Open Sans;
    font-size: 1rem;
    }

body table
    {
    margin-left: auto;
    margin-right: auto;
    text-align: center;
    }
body table tr td 
    {
    padding-left: 1rem;
    padding-right: 1rem;
    height: 1rem;
    }

body table tr td.on
    { color: green; }
body table tr td.off
    { color: red; }

th
    {
    background-color: #006fdd;
    color: #fff;
    padding: 5px;
    border-radius: 5px;
    }

body div#panel
    {
    width: 10rem;
    background-color: #1b1b1b;
    float: left;
    height: 100vh;
    padding: 0;
    margin: 0;
    padding-left: 1rem;
    }

body div#panel ul 
    {
    }

body div#panel ul li
    {
    list-style: none;
    padding: 0.5rem;
    }

body div#panel ul li a
    {
    text-decoration: none;
    color: white;
    }

body div#panel ul li a:hover
    {
    text-decoration: none;
    color: #006fdd;
    }
`;

const header = `
<!DOCTYPE html>
<html>
<head>
    <title>TerrarIO</title>
    <link rel="stylesheet" type="text/css" href="/default.css" media="screen" >
</head>
<body>
<div id="panel">
    <h2>TerrarIO</h2>
    <ul>
        <li><a href="/">Schedule</a></li>
        <li><a href="/devices">Devices</a></li>
        <li><a href="/">About</a></li>
    </ul>
</div>
`;

const footer = `
</body>
</html>
`;

module.exports =
    {
    header,
    footer,
    css,
    favicon
    }
